import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  getStartTutorial: [
    {
      type: "doc",
      label: "Get Started",
      id: "intro",
      className: "side-link-gif niwi-get-started",
    },
    {
      type: "doc",
      label: "Project Structure",
      id: "project-structure",
      className: "side-link-gif niwi-project",
    },
    {
      type: "category",
      label: "Built In Feature",
      className: "side-link-gif niwi-built-in",
      items: [
        {
          type: "autogenerated",
          dirName: "built-in-feature",
        },
      ],
    },
    {
      type: "category",
      label: "Authentication",
      className: "side-link-gif niwi-auth",
      items: [
        {
          type: "autogenerated",
          dirName: "authentication",
        },
      ],
    },
    {
      type: "doc",
      label: "Mini Apps",
      id: "mini-apps",
      className: "side-link-gif niwi-mini-apps sperate-top-navbar",
    },
    // {
    //   type: "category",
    //   label: "Testing",
    //   className: "side-link-gif niwi-testing",
    //   items: [
    //     {
    //       type: "autogenerated",
    //       dirName: "authentication",
    //     },
    //   ],
    // },
  ],
};

export default sidebars;
