import { LightDarkToggle } from "@/components/niwi-ui/light-dark-toggler/light-dark-toggler";
import ReactQueryProvider from "@/components/query-client-provider/query-client-provider";
import { getDarkModeCookie } from "@/feats/setting/actions/setting.action";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { Toaster } from "react-hot-toast";

// Importing Styles
import "@/components/niwi-blog/niwi-text-editor/styles/niwi-editor-code.css";
import "@/components/niwi-blog/niwi-text-editor/styles/niwi-editor-embedded.css";
import "@/components/niwi-blog/niwi-text-editor/styles/niwi-editor-emoji.css";
import "@/components/niwi-blog/niwi-text-editor/styles/niwi-editor-image.css";
import "@/components/niwi-blog/niwi-text-editor/styles/niwi-editor-line-break.css";
import "@/components/niwi-blog/niwi-text-editor/styles/niwi-editor-splash-image.css";
import "@/components/niwi-blog/niwi-text-editor/styles/niwi-editor-tool.css";
import "@/components/niwi-blog/niwi-text-editor/styles/niwi-editor.css";
import "@/styles/globals.css";
import "@/styles/niwi.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create niw! Starter",
  description: "Generated by niw! Starter",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isDarkMode = await getDarkModeCookie();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} niwi-body ${isDarkMode ? "dark" : ""}`}
      >
        <ReactQueryProvider>
          {children}
          <LightDarkToggle className="absolute top-5 right-5" />
          <Toaster />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
