import type { Metadata } from "next";
import localFont from "next/font/local";
import { Toaster } from "react-hot-toast";
import "@/styles/globals.css";
import "@/styles/niwi.css";
import { LightDarkToggle } from "@/components/niwi-ui/light-dark-toggler/light-dark-toggler";
import { getDarkModeCookie } from "@/feats/setting/actions/setting.action";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create niw! Starter",
  description: "Generated by niw! Starter",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isDarkMode = await getDarkModeCookie();
  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} niwi-body ${isDarkMode ? "dark" : ""}`}
      >
        {children}
        <LightDarkToggle className="absolute top-5 right-5" />
        <Toaster />
      </body>
    </html>
  );
}
