export default {
  code: "editor-code",
  heading: {
    h1: "editor-heading-h1",
    h2: "editor-heading-h2",
    h3: "editor-heading-h3",
    h4: "editor-heading-h4",
    h5: "editor-heading-h5",
  },
  image: "editor-image",
  link: "editor-link",
  list: {
    listitem: "editor-listitem",
    nested: {
      listitem: "editor-nested-listitem",
    },
    ol: "editor-list-ol",
    ul: "editor-list-ul",
  },
  ltr: "ltr",
  paragraph: "editor-paragraph",
  placeholder: "editor-placeholder",
  quote: "editor-quote",
  rtl: "rtl",
  text: {
    bold: "editor-text-bold",
    code: "editor-text-code",
    hashtag: "editor-text-hashtag",
    italic: "editor-text-italic",
    overflowed: "editor-text-overflowed",
    strikethrough: "editor-text-strikethrough",
    underline: "editor-text-underline",
    underlineStrikethrough: "editor-text-underlineStrikethrough",
  },

  // Code Highlight
  codeHighlight: {
    atrule: "editor-token-atrule",
    attr: "editor-token-attr",
    boolean: "editor-token-boolean",
    builtin: "editor-token-builtin",
    cdata: "editor-token-cdata",
    char: "editor-token-char",
    class: "editor-token-class",
    "class-name": "editor-token-class-name",
    comment: "editor-token-comment",
    constant: "editor-token-constant",
    deleted: "editor-token-deleted",
    doctype: "editor-token-doctype",
    entity: "editor-token-entity",
    function: "editor-token-function",
    important: "editor-token-important",
    inserted: "editor-token-inserted",
    keyword: "editor-token-keyword",
    namespace: "editor-token-namespace",
    number: "editor-token-number",
    operator: "editor-token-operator",
    prolog: "editor-token-prolog",
    property: "editor-token-property",
    punctuation: "editor-token-punctuation",
    regex: "editor-token-regex",
    selector: "editor-token-selector",
    string: "editor-token-string",
    symbol: "editor-token-symbol",
    tag: "editor-token-tag",
    url: "editor-token-url",
    variable: "editor-token-variable",
  },

  // Custom Theme
  niwiEmoji: "niwi-editor-emoji",
};
